<?php
namespace Admin\Controller;
use Admin\Controller\BaseController;

/**
 * 网站配置控制器
 * Created by PhpStorm.
 * User: admin
 * Date: 2016/7/20
 * Time: 12:12
 */
class SettingController extends BaseController {

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 查看网站设置
     * 修改网站设置
     */
    public function index() {
    	$this->assign('page_title', '网站设置');
    	if (IS_POST){
    		$model = M('settings');
    		//搜索表中已经存在的数据
    		$_data = $model->select();
    		//接收表单提交的数据
    		$post = $_POST;
    		if (is_array($post['signin'])){
    			$post['signin'] = array2string($post['signin']);
    		}
    		if (is_array($post['recharge'])){
    			$post['recharge'] = array2string($post['recharge']);
    		}
    		foreach ($post as $k => $v) {
    			// site_name
    			$bool = false;
    			$data = array();
    			//判断表单中的KEY是否存在于数据库中
    			foreach ($_data as $_d) {
    				if ($_d['key'] == $k) {
    					$bool = true;
    					break;
    				}
    			}
    			if ($bool == false) {
    				//添加
    				$data = array(
    						'key' => $k,
    						'value' => $v
    				);
    				$ok = $model->add($data);
    			} else {
    				//修改
    				$data = array(
    						'value' => $v
    				);
    				$where = array(
    						'key' => $k
    				);
    				$ok = $model->where($where)->save($data);
    			}
    		}
    		if ($ok !== false) {
    			$url = U("setting/index");
    			$this->success("数据保存成功", $url);
    		} else {
    			$url = U("setting/index");
    			$this->error("数据保存失败", $url);
    		}
    	}else{
    		$mysql = M('settings');
    		$data = $mysql->select();
    		$info = array();
    		for($i=0;$i<count($data);$i++){
    			$data_key = $data[$i]['key'];
    			if ($data_key=='signin'){
    				$info[$data_key] = string2array($data[$i]['value']);
    			}elseif ($data_key=='recharge'){
    				$info[$data_key] = string2array($data[$i]['value']);
    			}else{
    				$info[$data_key] = $data[$i]['value'];
    			}
    			
    		}
    		$this->assign('data',$info);
    		$this->display();
    	}
    }
}