<?php
namespace Admin\Controller;

use Admin\Controller\BaseController;
use Boris\DumpInspector;

/**
 * 幻灯片控制器
 * Created by PhpStorm.
 * User: admin
 * Date: 2016/7/20
 * Time: 12:13
 *
 * 幻灯片可以管理游戏，首页
 */
class SliderController extends BaseController
{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 幻灯片列表
     */
    public function index()
    {
        $this->assign("page_title", "幻灯片列表");
        $seek = trim($_POST['seek']);
        $pageSize = C('page_size');
        $page = I("get.p",1,"intval");
        if (empty($seek)) {
            $model = M('slider a');
            //$count = $model->count();
            //$model->join("")
            $list = $model
                ->field("a.*, b.title as `netbar_title`, d.region_name")
                ->join("LEFT JOIN yw_user_netbar b ON a.netbar_id = b.user_id")
                ->join("LEFT JOIN yw_user c ON b.user_id = c.id ")
                ->join("LEFT JOIN yw_region d ON c.city_id = d.region_id")
                ->order("a.add_time DESC")
                ->page($page, $pageSize)
                ->select();

            $count = $model
                ->field("a.*, b.title as `netbar_title`, d.region_name")
                ->join("LEFT JOIN yw_user_netbar b ON a.netbar_id = b.user_id")
                ->join("LEFT JOIN yw_user c ON b.user_id = c.id ")
                ->join("LEFT JOIN yw_region d ON c.city_id = d.region_id")
                ->order("a.add_time DESC")
                ->count();
            //$count = count($list);
        } else {
            $model = M('slider a');
            $map = array();
            $map['a.title'] = array("LIKE", "%$seek%");
            $map['d.region_name'] = array("LIKE", "%$seek%");
            $map['_logic'] = 'OR';
            $list = $model
                ->field("a.*, b.title as `netbar_title`, d.region_name")
                ->join("LEFT JOIN yw_user_netbar b ON a.netbar_id = b.user_id")
                ->join("LEFT JOIN yw_user c ON b.user_id = c.id ")
                ->join("LEFT JOIN yw_region d ON c.city_id = d.region_id")
                ->order("a.add_time DESC")
                ->where($map)
                ->page($page, $pageSize)
                ->select();


            $count = $model
                ->field("a.*, b.title as `netbar_title`, d.region_name")
                ->join("LEFT JOIN yw_user_netbar b ON a.netbar_id = b.user_id")
                ->join("LEFT JOIN yw_user c ON b.user_id = c.id ")
                ->join("LEFT JOIN yw_region d ON c.city_id = d.region_id")
                ->order("a.add_time DESC")
                ->where($map)
                ->count();
            //$count = $model->where(" title like '%$seek%' ")->count();
            //$list = $model->where(" title like '%$seek%' ")->select();
            //$count = count($list);
            $this->assign('keyword', $seek);
        }
        $Page = new \Think\Page($count, $pageSize);
        $Page -> setConfig('prev','上一页');
        $Page -> setConfig('next','下一页');
        $page = $Page->show();

        $this->assign('page', $page);
        $this->assign('list', $list);
        $this->display();
    }

    /**
     * 添加
     */
    public function add()
    {
        if (IS_GET) {
            $this->assign("page_title", "幻灯片添加");
            # 选择官方对战
//         	$warModel = M('war');
//         	$warData = $warModel->where("type = 1")->select();
            # 选择游戏
            $games = M('games')->select();
            $this->assign('games', $games);

            // 选择比赛
            $wars = M("war")->select();
            $this->assign('wars', $wars);

            $this->display();
        } else {
            $model = D("slider");
            $_POST['add_time'] = date('Y-m-d H:i:s');
            $_POST['img_num'] = count($_POST['images']);
            $_POST['images'] = base64_encode(serialize($_POST['images']));
            $url = U('Slider/index');
            if ($model->create()) {
                if ($model->add()) {
                    $this->success("数据添加成功",$url);
                } else {
                    $this->error("数据添加失败：" . $model->getError(),$url);
                }
            } else {
                $this->error("数据添加失败：" . $model->getError(),$url);
            }
        }
    }

    /**
     * 修改
     */
    public function edit()
    {
        if (IS_GET) {
            $this->assign("page_title", "幻灯片编辑");
            $id = $_GET['id'];
            $model = D('slider');
            $data = $model->where("id = $id")->find();
            $img = unserialize(base64_decode($data['images']));
            $this->assign('img', $img);
            $this->assign('num', $data['img_num']);
            $this->assign('data', $data);
            #目前选择的网吧
            if ($data['netbar_id']) {
                $netbar = M('user_netbar')->where(" user_id = " . $data['netbar_id'] . " ")->find();
                $this->assign('netbar', $netbar);
            }

            # 选择游戏
            $games = M('games')->select();
            $this->assign('games', $games);
            $this->assign('game_id', $data['game_id']);

            // 选择比赛
            $wars = M("war")->select();
            $this->assign('wars', $wars);
            $this->assign('war_id', $data['war_id']);

            $this->display();
        } else {
            $model = D("slider");
            $_POST['img_num'] = count($_POST['images']);
            $_POST['images'] = base64_encode(serialize($_POST['images']));
            $url = U('Slider/index');
            if ($model->create()) {
                if ($model->save() !== false) {
                    $this->success("数据修改成功",$url);
                } else {
                    $this->error("数据修改失败：" . $model->getError(),$url);
                }
            } else {
                $this->error("数据修改失败：" . $model->getError(),$url);
            }
        }
    }

    /**
     * 获取所有游戏数据
     */
    public function gameSelect()
    {
        $model = D('game');
        $data = $model->getGames();
        echo json_encode($data);
    }

    /**
     * 删除幻灯片
     * @param $id
     */
    public function del($id)
    {
        $model = D('slider');
        if ($model->delete($id)) {
            $this->success('删除成功');
        } else {
            $this->error('删除失败');
        }
    }

    /**
     * 官方战场轮播图
     */
    public function war($id)
    {
        if (IS_GET) {
            if (empty($id)) {
                $this->error('缺少必要参数');
            } else {
                $isNewRecord = 1;
                $this->assign('war_id', $id);
                $num = 0;
                $this->assign("page_title", "官方幻灯片编辑");
                $data_slider = M('slider')->where(" war_id = $id ")->find();
                if ($data_slider) {
                    $this->assign('model', $data_slider);
                    $img = unserialize(base64_decode($data_slider['images']));
                    $this->assign('img', $img);
                    $num = $data_slider['num'];
                    $isNewRecord = 0;
                    $slider_id = $data_slider['id'];
                    $this->assign("id", $slider_id);
                }
                if (empty($num)) {
                    $num = 0;
                }

                $this->assign("isNewRecord", $isNewRecord);
                $this->assign('num', $num);
                $model = M("war a");
                $data = $model
                    ->field("a.*, b.title as `netbar_title`")
                    ->join("LEFT JOIN yw_user_netbar b ON a.netbar_id = b.user_id")
                    ->where(array('a.id'=>$id))
                    ->find();
                if ($data) {

                    $this->assign('data', $data);

                    // 目前选择的网吧
                    if ($data['netbar_id']) {
                        $netbar = M('user_netbar')->where(" user_id = " . $data['netbar_id'] . " ")->find();
                        $this->assign('netbar', $netbar);
                    }
                    $this->assign('game_id', $data['game_id']);
                    $this->assign('war_id', $id);

                } else {
                    //$this->error("未搜索到数据");
                }

                // 选择游戏
                $games = M('games')->select();
                $this->assign('games', $games);

                // 选择比赛
                $wars = M("war")->select();
                $this->assign('wars', $wars);

                $this->display();

            }
        } else {
            $model = D("slider");
            $_POST['add_time'] = date('Y-m-d H:i:s');
            $_POST['img_num'] = count($_POST['images']);
            $_POST['images'] = base64_encode(serialize($_POST['images']));

            $isNewRecord = $_POST['isNewRecord'];

            if ($model->create()) {

                if ($isNewRecord) {
                    //添加
                    if (false !== $model->add()) {
                        $url = U("war/index");
                        $this->success("数据添加成功", $url);
                    } else {
                        $this->error("数据添加失败：" . $model->getError());
                    }
                } else {

                    if (false !== $model->save()) {
                        $url = U("war/index");
                        $this->success("数据修改成功", $url);
                    } else {
                        $this->error("数据修改失败：" . $model->getError());
                    }
                }
            } else {
                $this->error("数据添加失败：" . $model->getError());
            }
        }
    }

}