<?php
namespace Admin\Controller;
use Admin\Controller\BaseController;

/**
 * 游戏对战控制器
 * Created by PhpStorm.
 * User: admin
 * Date: 2016/7/20
 * Time: 12:10
 */
class WarController extends BaseController
{

    /**
     * 初始化函数
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 列表
     */
    public function index()
    {
        $this->assign("page_title", "游戏桌列表");
        $model = M('war t1');
        $seek = trim($_POST['seek']);
        $status = isset($_GET['status'])?$_GET['status']:'all';
        $this->assign('status',$status);
        $pageSize = C('page_size');
        if ($status=='all'){
	        if (empty($seek)){
	        	$count = $model->field(" t1.*,t2.real_name,t3.title game_title,t4.title netbar_title ")->join("left join yw_user t2 on t1.user_id = t2.id  ")->join("left join yw_games t3 on t1.game_id = t3.id ")->join("left join yw_user_netbar t4 on t1.netbar_id = t4.user_id")->count();
	        	$list = $model->field(" t1.*,t2.real_name,t3.title game_title,t4.title netbar_title,t3.thumb ")->join("left join yw_user t2 on t1.user_id = t2.id  ")->join("left join yw_games t3 on t1.game_id = t3.id ")->join("left join yw_user_netbar t4 on t1.netbar_id = t4.user_id")->order(' t1.add_time desc ') ->page($_GET['p'],$pageSize)->select();
	        }else{
	        	$count = $model->field(" t1.*,t2.real_name,t3.title game_title,t4.title netbar_title ")->join("left join yw_user t2 on t1.user_id = t2.id  ")->join("left join yw_games t3 on t1.game_id = t3.id ")->join("left join yw_user_netbar t4 on t1.netbar_id = t4.user_id")->where(" t3.title like '%$seek%' ")->count();
	        	$list = $model->field(" t1.*,t2.real_name,t3.title game_title,t4.title netbar_title,t3.thumb ")->join("left join yw_user t2 on t1.user_id = t2.id  ")->join("left join yw_games t3 on t1.game_id = t3.id ")->join("left join yw_user_netbar t4 on t1.netbar_id = t4.user_id")->order(' t1.add_time desc ') ->page($_GET['p'],$pageSize)->where("t3.title like '%$seek%'")->select();
	        	$this->assign('keyword',$seek);
	        }
        }else{
        	if (empty($seek)){
        		$count = $model->field(" t1.*,t2.real_name,t3.title game_title,t4.title netbar_title ")->join("left join yw_user t2 on t1.user_id = t2.id  ")->join("left join yw_games t3 on t1.game_id = t3.id ")->join("left join yw_user_netbar t4 on t1.netbar_id = t4.user_id")->where(" t1.status = '$status' ")->count();
        		$list = $model->field(" t1.*,t2.real_name,t3.title game_title,t4.title netbar_title,t3.thumb ")->join("left join yw_user t2 on t1.user_id = t2.id  ")->join("left join yw_games t3 on t1.game_id = t3.id ")->join("left join yw_user_netbar t4 on t1.netbar_id = t4.user_id")->where(" t1.status = '$status' ")->order(' t1.add_time desc ') ->page($_GET['p'],$pageSize)->select();
        	}else{
        		$count = $model->field(" t1.*,t2.real_name,t3.title game_title,t4.title netbar_title ")->join("left join yw_user t2 on t1.user_id = t2.id  ")->join("left join yw_games t3 on t1.game_id = t3.id ")->join("left join yw_user_netbar t4 on t1.netbar_id = t4.user_id")->where(" t3.title like '%$seek%' and t1.status = '$status' ")->count();
        		$list = $model->field(" t1.*,t2.real_name,t3.title game_title,t4.title netbar_title,t3.thumb ")->join("left join yw_user t2 on t1.user_id = t2.id  ")->join("left join yw_games t3 on t1.game_id = t3.id ")->join("left join yw_user_netbar t4 on t1.netbar_id = t4.user_id")->order(' t1.add_time desc ') ->page($_GET['p'],$pageSize)->where("t3.title like '%$seek%' and t1.status = '$status'")->select();
        		$this->assign('keyword',$seek);
        	}
        }
        
        $Page = new \Think\Page($count,$pageSize);
        $page = $Page->show();
        $this->assign('page',$page);
        $this->assign('list',$list);
        $this->display();
    }

    public function details($id)
    {
        $this->assign("page_title", "游戏桌详情");
        $model = M('war t1');
        $list = $model->field(" t1.*,t2.real_name,t3.title game_title,t4.title netbar_title,t3.thumb ")->join("left join yw_user t2 on t1.user_id = t2.id  ")->join("left join yw_games t3 on t1.game_id = t3.id ")->join("left join yw_user_netbar t4 on t1.netbar_id = t4.user_id")->where(" t1.id = $id ")->find();
        $this->assign('data',$list);
        $this->display();
    }
    /**
     * 删除对战信息
     */
    public function del($id){
    	$model = M('war');
    	$return = $model->delete($id); 
    	if ($return){
    		M('war_team')->where(" war_id = $id ")->delete();
    		$this->success('删除成功');
    	}else{
    		$this->error('删除失败');
    	}
    }
    
    /**
     * 添加官方对战
     */
    public function add(){
    	if (IS_POST){
    		$_POST['remain'] = $_POST['times'];
    		$_POST['type'] = 1;
    		$_POST['status'] = 'doing';
    		$_POST['add_time'] = date('Y-m-d H:i:s');
			
    		if (M('war')->add($_POST)){
    			$this->success('添加成功');
    		}else{
    			$this->error('添加失败');
    		}
    	}else{
    		$this->assign("page_title", "添加官方对战");
    		# 游戏列表
    		$gameModel = M('games');
    		$games = $gameModel->select();
    		$this->assign('games',$games);
    		
    		# 网吧列表
    		$netbar = M('user_netbar')->where("status = 1")->select();
    		$this->assign('netbar',$netbar);
    		
    		$this->display();
    	}
    }


}